apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: samples-discovery-server
  name: samples-discovery-server
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
  selector:
    app: samples-discovery-server
status:
  loadBalancer: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: samples-discovery-server
  name: samples-discovery-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: samples-discovery-server
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samples-discovery-server
    spec:
      containers:
      - image: flomesh/samples-discovery-server:latest
        name: samples-discovery-server
        resources: {}
        ports:
        - containerPort: 8761
status: {}
