apiVersion: v1
kind: Service
metadata:
  name: pipy-repo
  namespace: pipy-infra
spec:
  ports:
  - port: 6060
    protocol: TCP
    targetPort: 6060
  selector:
    control-plane: controller-manager
  sessionAffinity: None
  type: ClusterIP